name: coverage-redesign
root: env:IH_HOME
repos:
    - id: project-coverage-redesign
      path: project-coverage-redesign
      tags: []
    - id: coverage
      path: coverage
      tags: []
    - id: customer-configuration
      path: customer-configuration
      tags: []
    - id: member-sponsorship
      path: member-sponsorship
      tags: []
    - id: realtime-eligibility
      path: realtime-eligibility
      tags: []
    - id: support-tools
      path: support-tools
      tags: []
    - id: go-common
      path: go-common
      tags: []
    - id: proto-common
      path: proto-common
      tags: []
    - id: surveyor
      path: surveyor
      tags: []
ide:
    vscode:
        workspace_file: coverage-redesign.code-workspace
    intellij:
        project_dir: .
        module_prefix: meta_
